# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-170516909-1'

menu:
- {name: 'Portfolio', folder: 'pages', file: 'portfolio.html'}
- {name: 'Research', folder: 'pages', file: 'research.html'}
- {name: 'About', folder: 'pages', file: 'aboutme.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/lenikrsova'}
- {icon: 'envelope', link: 'mailto:lkrsova@syr.edu'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy readiing...'

post_date_prefix: 'Written on'
